
language: node_js
node_js:
  - "12"

install:
  - yarn
  - yarn run build

script:
  - yarn run test
  - yarn run lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
